In [1]:
import numpy as np
from classifier import preprocessing as cfp

In [2]:
arr = [[1,2,3,4,5], [2,3,4,5,6], [3,4,5,6,7]]

In [3]:
arr = np.array(arr)

In [4]:
print(np.expand_dims(arr, axis = 0).T.shape)

(5, 3, 1)


In [5]:
preprocessor = cfp()

In [6]:
data = preprocessor.processedData(predata = arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
max [[1 2 3 4 5 5]
 [2 3 4 5 6 6]
 [3 4 5 6 7 7]]
min [[1 2 3 4 5 5 1]
 [2 3 4 5 6 6 2]
 [3 4 5 6 7 7 3]]
avg [[1. 2. 3. 4. 5. 5. 1. 3.]
 [2. 3. 4. 5. 6. 6. 2. 4.]
 [3. 4. 5. 6. 7. 7. 3. 5.]]
abs [[ 1.          2.          3.          4.          5.          5.
   1.          3.          7.41619849]
 [ 2.          3.          4.          5.          6.          6.
   2.          4.          9.48683298]
 [ 3.          4.          5.          6.          7.          7.
   3.          5.         11.61895004]]
rms [[ 1.          2.          3.          4.          5.          5.
   1.          3.          7.41619849  3.31662479]
 [ 2.          3.          4.          5.          6.          6.
   2.          4.          9.48683298  4.24264069]
 [ 3.          4.          5.          6.          7.          7.
   3.          5.         11.61895004  5.19615242]]


In [7]:
print(data)

[[ 1.          2.          3.          4.          5.          5.
   1.          3.          7.41619849  3.31662479]
 [ 2.          3.          4.          5.          6.          6.
   2.          4.          9.48683298  4.24264069]
 [ 3.          4.          5.          6.          7.          7.
   3.          5.         11.61895004  5.19615242]]
